// Generated by CoffeeScript 1.6.2
var RestAdapter, ajax,
  __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

ajax = require('ajax');

RestAdapter = (function() {
  function RestAdapter(options) {
    this.count = __bind(this.count, this);
    this.find = __bind(this.find, this);
    this.remove = __bind(this.remove, this);
    this.update = __bind(this.update, this);
    this.create = __bind(this.create, this);
    this._end_point = __bind(this._end_point, this);
    this.initialize = __bind(this.initialize, this);    this.collection_name = options ? options.collection_name : void 0;
    this.cursor_update = void 0;
  }

  RestAdapter.prototype.initialize = function() {};

  RestAdapter.prototype._end_point = function(name) {
    return '/api/' + this.collection_name + '/' + name;
  };

  RestAdapter.prototype.create = function(query, cb) {
    var _this = this;
    return ajax({
      url: this._end_point('create'),
      type: 'POST',
      dataType: 'json',
      data: query,
      success: function(data, textStatus, jqXHR) {
        cb(data.err);
        return _this.cursor_update();
      }
    });
  };

  RestAdapter.prototype.update = function(query, cb) {
    var _this = this;
    return ajax({
      url: this._end_point('update'),
      type: 'PUT',
      dataType: 'json',
      data: query,
      success: function(data, textStatus, jqXHR) {
        cb(data.err);
        return _this.cursor_update();
      }
    });
  };

  RestAdapter.prototype.remove = function(query, cb) {
    var _this = this;
    return ajax({
      url: this._end_point('remove'),
      type: 'DELETE',
      dataType: 'json',
      data: query,
      success: function(data, textStatus, jqXHR) {
        cb(data.err);
        return _this.cursor_update();
      }
    });
  };

  RestAdapter.prototype.find = function(query, cb) {
    var _this = this;
    return ajax({
      url: this._end_point('find'),
      type: 'GET',
      dataType: 'json',
      data: query,
      success: function(data, textStatus, jqXHR) {
        return cb(data.err, data.docs);
      }
    });
  };

  RestAdapter.prototype.count = function(query, cb) {
    var _this = this;
    return ajax({
      url: this._end_point('count'),
      type: 'GET',
      dataType: 'json',
      data: query,
      success: function(data, textStatus, jqXHR) {
        return cb(data.err, data.count);
      }
    });
  };

  return RestAdapter;

})();

module.exports = RestAdapter;
