// Generated by CoffeeScript 1.6.2
var SocketAdapter,
  __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

SocketAdapter = (function() {
  SocketAdapter.create_socket = function(name_space, io) {
    var socket;
    socket = io.connect('/socket_api_' + name_space);
    return socket;
  };

  function SocketAdapter(options) {
    this.count = __bind(this.count, this);
    this.find = __bind(this.find, this);
    this.remove = __bind(this.remove, this);
    this.update = __bind(this.update, this);
    this.create = __bind(this.create, this);
    this.initialize = __bind(this.initialize, this);
    this._event = __bind(this._event, this);    this.socket = options.socket ? options.socket : SocketAdapter.create_socket('', io);
    this.collection_name = options.collection_name;
    this.cursor_update = void 0;
  }

  SocketAdapter.prototype._event = function(name) {
    return this.collection_name + " " + name;
  };

  SocketAdapter.prototype.initialize = function() {
    var _this = this;
    this.socket.on('connect', function() {
      return console.log('-- connected --', _this.name_space);
    });
    return this.socket.on(this._event('update'), function(data) {
      console.log('update???');
      return _this.cursor_update();
    });
  };

  SocketAdapter.prototype.create = function(query, cb) {
    return this.socket.emit(this._event('create'), query, cb);
  };

  SocketAdapter.prototype.update = function(query, cb) {
    return this.socket.emit(this._event('update'), query, cb);
  };

  SocketAdapter.prototype.remove = function(query, cb) {
    return this.socket.emit(this._event('remove'), query, cb);
  };

  SocketAdapter.prototype.find = function(query, cb, cursor) {
    return this.socket.emit(this._event('find'), query, cb);
  };

  SocketAdapter.prototype.count = function(query, cb, cursor) {
    return this.socket.emit(this._event('count'), query, cb);
  };

  return SocketAdapter;

}).call(this);

module.exports = SocketAdapter;
